### PR TITLE
fix: Full name validation in register page Issue#1250

### PR DESCRIPTION
**Pull request by jciasenza**
### Description

What changed?

When registering as a user on the MFE Authentication Registration tab, in the Full Name field
Validate that it contains at least 3 up to 30 characters
since it only allowed 1, and I also made a validation so that it does not allow special characters or numbers, only alphabets.

Issue: 
(https://github.com/openedx/frontend-app-authn/issues/1250)

Screenshot from 2024-11-05 11-00-29

And I have modified the error text:

Screenshot from 2024-11-05 11-00-14

#### How Has This Been Tested?

And Testing OK

If something needs to be modified, let me know, thank you!!!
Atte
Juan Carlos (Aulasneo)

Developer Checklist

Test suites passing
Documentation and test plan updated, if applicable
Received code-owner approving review

### CODE REVIEW

**Comment by jciasenza** [comment]
I made a new change in the validation since it is necessary to readable characters for different languages ​​such as letters with accents, umlauts and other language characters: 
image

**Comment by jciasenza** [comment]
Hi, [itsjeyd](https://github.com/itsjeyd) Could you check this PR

**Comment by jciasenza** [comment]
Hi @brian-smith-tcril , what do you think of this change I made to the validation of the fullname field? 
@hinakhadim, had asked for it in issue #1250.
If it's ok, it could be merged !!!

**Comment by mphilbrick211** [comment]
@openedx/2u-infinity this is ready for review. Thanks!

**Comment by jciasenza** [comment]
Thanks @mphilbrick211  !!!

**Comment by brian-smith-tcril** [comment]
It looks like this is a product change that needs to go through product review. I see @hinakhadim made the original issue - did that make it through review? https://openedx.atlassian.net/wiki/spaces/COMM/pages/3875962884/How+to+submit+an+open+source+contribution+for+Product+Review

**Comment by jciasenza** [comment]
Ok, so I hope they approve it.

**Comment by ormsbee** [comment]
@jciasenza: Please note that human names are really, really complicated, which is part of why the validation for this is so relaxed.

For instance:

> Validate that it contains at least 3 up to 30 characters

[Korean names](https://en.wikipedia.org/wiki/Korean_name) are usually three characters (1 for the family, 2 for the given), but they can be as short as two (1 for family, 1 for given). I'd hazard a guess that single character names do exist out there somewhere.

On the other hand, Hawaiian names can be very long. There's an article about a woman whose _family name alone_ is [36 characters](https://www.usatoday.com/story/news/nation/2013/12/30/hawaii-long-name/4256063/).

I know those just off the top of my head, because my mother's family is Korean and I grew up in Hawaii.

> I also made a validation so that it does not allow special characters or numbers, only alphabets.

Are dashes, apostrophes, and [okinas](https://en.wikipedia.org/wiki/%CA%BBOkina) counted as letters for the purposes of Unicode? (I honestly don't know the answer.) Regardless, again, I don't think we want to make any assumptions here. 

[Falsehoods programmers believe about names](https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/) gives an overview of some of these issues.

The question is what we're trying to guard against here. If the user makes a mistake, they can always change their name later. If the user is intentionally trying to put false data into the system, then we can't really stop that with extra rules–they'll just put false data that conforms to those rules. I don't think it's worth the risk of blocking legitimate names in order to try to prevent that.

**Comment by jciasenza** [comment]
Hello @ormsbee,  I performed the validations as requested by
@hinakhadim in issue #1250, but I agree with what you think, there is no problem leaving it without validations.
I also think that it is extremely difficult to have such a long name to display in the different components of the platform.

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-1348-0d554a.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-1348-0d554a.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1348-0d554a-51564656-8591535728-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1348-0d554a-51564656-8591535728-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1348-0d554a-51564656-8591535728-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-1348-0d554a.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-1348-0d554a.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1348-0d554a-51564656-8600489812-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1348-0d554a-51564656-8600489812-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1348-0d554a-51564656-8600489812-tutor-requirements.txt)

**Comment by open-craft-grove** [comment]
Sandbox deployment successful 🚀
🎓 [LMS](https://pr-1348-0d554a.sandboxes.opencraft.hosting)
📝 [Studio](https://studio.pr-1348-0d554a.sandboxes.opencraft.hosting)
ℹ️ [Grove Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1348-0d554a-51564656-8653010038-tutor-config.yml), [Tutor Config](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1348-0d554a-51564656-8653010038-grove-config.yml), [Tutor Requirements](https://axim-sandbox-build-logs-4626178240.nyc3.digitaloceanspaces.com/pr-1348-0d554a-51564656-8653010038-tutor-requirements.txt)

**Comment by ormsbee** [comment]
@jciasenza: I'm closing this PR until @hinakhadim pushes https://github.com/openedx/frontend-app-authn/issues/1250 through the product review process. It's possible that we'll want to add more validation to the name, but I don't believe that the rules added by this PR are acceptable, especially as they  would exclude multiple people that I personally know.

If the problem we're trying to solve is that it's difficult to display the full name in places in the UI, that's something that can be addressed by separating the casual name we call them by and the full name that has to go on formal things like their certificate (e.g. "Dave" vs. "David Ormsbee"). Which again, would have to go through product review.

**Comment by ormsbee** [comment]
@jciasenza: If you're looking for small tasks to pick up, you can look at [bugs reported during Sumac release testing](https://github.com/openedx/wg-build-test-release/issues?q=is%3Aopen+is%3Aissue+label%3Asumac).

I haven't looked through the full list, but I filed a few related to Files and Uploads that I hope will be straightforward to fix:

* https://github.com/openedx/wg-build-test-release/issues/424
* https://github.com/openedx/wg-build-test-release/issues/425
* https://github.com/openedx/wg-build-test-release/issues/426

**Pull request closed without merging**
