### PR TITLE
fix: Fixed spacing in tablet version

### PR DESCRIPTION
**Pull request by vladislavkeblysh**
### Fixed spacing in tablet version

Fixed spacing in authn title in tablet version

#### Screenshots/sandbox (optional):

Screenshot 2023-09-19 at 12 52 15

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @vladislavkeblysh!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by zainab-amir** [comment]
We have created a ticket in the backlog for the review

CC: @mphilbrick211

**Comment by zainab-amir** [comment]
We have not been able to reproduce the issue on master branch. Also your changes affect the accent color design. 

https://github.com/openedx/frontend-app-authn/assets/40633976/37bd45c6-a79d-433b-a128-d1b27403a7a8

**Comment by mphilbrick211** [comment]
Hi @vladislavkeblysh! Just flagging Zainab's comment above!

**Comment by mphilbrick211** [comment]
Hi @zainab-amir! Would you be able to re-run the checks on this PR? It bounced back to needing approval.

**Comment by mphilbrick211** [comment]
Hi @vladislavkeblysh! Flagging that there is a failing check.

**Comment by vladislavkeblysh** [comment]
@mphilbrick211 The coverage issues are not related to the new code added in this PR. It seems like this has been carrying over from previous PRs.

**Comment by mphilbrick211** [comment]
Hi @vladislavkeblysh! I spoke internally with my team, and they recommended that you rebase to see if that clears the codecov failure. If it's still showing up after that, we'll see what else we can do.

**Comment by vladislavkeblysh** [comment]
Hi @mphilbrick211! The branch was rebased.

**Review by zainab-amir — CHANGES_REQUESTED** [review]
I tested your change locally and its not working for me:

Screenshot 2023-11-27 at 3 13 25 PM

One suggestion I have is that maybe you can use the paragon classes to achieve this. Its not an issue on Medium layout and for small screen just use `mr-2`. See below for details

https://github.com/openedx/frontend-app-authn/assets/40633976/5b2645d1-ef4a-4e6e-9c08-9c63af039112

**Comment by vladislavkeblysh** [comment]
@zainab-amir I think, we must to use default space in this case
I have fixed it on mobile view, can you check, please?

**Review by zainab-amir — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@vladislavkeblysh 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-authn&entry.867055334=https://github.com/openedx/frontend-app-authn/pull/1062&entry.1484655318=https://github.com/vladislavkeblysh&entry.752974735=2023-09-19+10:02&entry.1917517419=2023-11-28+05:47&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
