### PR TITLE
feat: Auth form visual enhancements (olive)

### PR DESCRIPTION
**Pull request by Lunyachek**
### Description

Cosmetic improvements for the login/registration page. Changes in React are related to the situation when third-party login providers is disabled, but when switching between Login and Registration tabs, we still see a preloader that is not necessary in this situation.

https://user-images.githubusercontent.com/19806032/222164313-f1e985d9-47e1-4b18-8b27-8280f5c6a7fd.mov

And sass changes are related to the suggested username field, which is too short and can be extended to match the neighboring inputs.

image1

After making our changes, we no longer see preloaders in cases where third-party login providers are turned off.

https://user-images.githubusercontent.com/19806032/222174870-e76fe894-1a63-448b-bc08-ffd9df8dca0b.mov

And suggested username field looks pretty

Снимок экрана 2023-03-01 в 16 46 17

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @Lunyachek!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.

**Comment by mphilbrick211** [comment]
Hi @zainab-amir! Product is all set with this. Please review and merge if all looks good to you. Thanks!

**Comment by mphilbrick211** [comment]
> Hi @zainab-amir! Product is all set with this. Please review and merge if all looks good to you. Thanks!

Hi @zainab-amir - friendly ping on this :)

**Comment by zainab-amir** [comment]
@mphilbrick211 the change in master branch is already in review and waiting for author: https://github.com/openedx/frontend-app-authn/pull/767
This is the same change but for the olive branch. Same changes are required here too.

**Review by syedsajjadkazmii — APPROVED** [review]

**Comment by openedx-webhooks** [comment]
@Lunyachek 🎉 Your pull request was merged!  Please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-authn&entry.867055334=https://github.com/openedx/frontend-app-authn/pull/766&entry.1484655318=https://github.com/Lunyachek&entry.752974735=2023-03-01+14:56&entry.1917517419=2024-04-19+05:56&entry.2133058324=Yes) so we can improve your experience in the future.

**Pull request merged**
