### PR TITLE
Fix order numbers of steps in README

### PR DESCRIPTION
**Pull request by serhatgktp**
### Description

Fixes numbers of steps in the README.

#### JIRA

N/A

#### How Has This Been Tested?

N/A

#### Merge Checklist

* [ ] If your update includes visual changes, have they been reviewed by a designer? Send them a link to the Sandbox, if applicable.
* [ ] Is there adequate test coverage for your changes?

#### Post-merge Checklist

* [ ] Deploy the changes to prod after verifying on stage or ask **@openedx/vanguards** to do it. 
* [ ] 🎉 🙌 Celebrate! Thanks for your contribution.

### CODE REVIEW

**Comment by openedx-webhooks** [comment]
Thanks for the pull request, @serhatgktp!  Please note that it may take us up to several weeks or months to complete a review and merge your PR.

Feel free to add as much of the following information to the ticket as you can:
- supporting documentation
- [Open edX discussion forum threads](https://discuss.openedx.org/)
- timeline information ("this must be merged by XX date", and why that is)
- partner information ("this is a course on edx.org")
- any other information that can help Product understand the context for the PR

All technical communication about the code itself will be done via the GitHub pull request interface. As a reminder, [our process documentation is here](http://edx-developer-guide.readthedocs.org/en/latest/process/overview.html).


Please let us know once your PR is ready for our review and all tests are green.


:warning: We can't start reviewing your pull request until you've submitted a     [signed contributor agreement](https://openedx.org/cla)     or indicated your institutional affiliation. Please see the [CONTRIBUTING](https://github.com/openedx/.github/blob/master/CONTRIBUTING.md)     file for more information.     If you've signed an agreement in the past, you may need to re-sign.  See     [The New Home of the Open edX Codebase](https://open.edx.org/blog/the-new-home-of-the-open-edx-codebase/)     for details.

    
Once you've signed the CLA, please allow 1 business day for it to be processed.  After this time, you can re-run the     CLA check by editing the PR title.  If the problem persists, you can tag the `@openedx/cla-problems` team in a     comment on your PR for further assistance.

**Comment by serhatgktp** [comment]
Hi Michelle,

I’ve already filled out the form twice. I’m not sure I’ll fill it out again.
It’s just a typo fix in the README anyways. I’m sure the core contributors can just change it themselves if they truly care for it.

Best,
Efkan
________________________________

**Comment by mphilbrick211** [comment]
Hi @serhatgktp! I checked on this for you, and we've received your corrected form (with the updated email address). It's awaiting review, and should be good-to-go in the next day or so. I will keep you posted if anything changes, but it's with our legal counsel at the moment for approval.

**Comment by e0d** [comment]
Hi @serhatgktp , we need to have a valid Contributor License Agreement (CLA) in place for all contributions.  See the welcome message above for the details about how to enroll.  The process is different depending upon whether you are making this contribution as an individual or on behalf of your employer.

**Comment by e0d** [comment]
@serhatgktp 
I notice there are some commit-lint failures.  Please note that we use conventional commits across Open edX projects.  You can read about the details [here](https://open-edx-proposals.readthedocs.io/en/latest/best-practices/oep-0051-bp-conventional-commits.html#type).  Can you please amend your commit messages to follow our standard?

**Comment by openedx-webhooks** [comment]
@serhatgktp Even though your pull request wasn’t merged, please take a moment  to [answer a two question survey](https://docs.google.com/forms/d/e/1FAIpQLSceJOyGJ6JOzfy6lyR3T7EW_71OWUnNQXp68Fymsk3MkNoSDg/viewform?usp=pp_url&entry.1671973413=openedx/frontend-app-authn&entry.867055334=https://github.com/openedx/frontend-app-authn/pull/1005&entry.1484655318=https://github.com/serhatgktp&entry.752974735=2023-07-27+20:15&entry.1917517419=2023-08-16+21:19&entry.2133058324=No) so we can improve your experience in the future.

**Pull request closed without merging**
